# Generated by Django 3.2.7 on 2021-09-17 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0007_auto_20210917_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='cooking', max_length=255),
        ),
    ]
